baseURL = "https://herbhuang.com/"
title = "🪴 Herb's Garden"
theme = "typographical"
enableRobotsTXT = true
enableGitInfo = true
languageCode = "en-us"
hasCJKLanguage=true

[permalinks]
post = "/post/:year-:month-:day-:title/"
poem = "/poem/:year-:month-:day-:title/"
page = "/:title/"

[author]
name = "Herb Huang"
email = "me@herbhuang.com"

[menu]
    [[menu.main]]
    identifier = "archive"
    pre = "<i class='fas fa-archive'></i>"
    title = "Archive"
    url = "/archive/"
    weight = 1
    [[menu.main]]
    identifier = "about"
    pre = "<i class='fas fa-info'></i>"
    title = "About"
    url = "/about/"
    weight = 9
    [[menu.main]]
      identifier = "posts"
    pre = "<i class='fas fa-book'></i>"
      title = "Posts"
      url = "/post/"
      weight = 2
    [[menu.main]]
      identifier = "poem"
    pre = "<i class='fas fa-scroll'></i>"
      title = "Poem"
      url = "/poem/"
      weight = 3


[params]
    css = ["_custom.css"]
    AccentColour = "#6da94d"
    MonospaceFont = "IBM Plex Mono"
    SerifFont = "Alegreya, \"Zhuque Fangsong (technical preview)\", \"Noto Serif SC\""
    SansSerifFont = "\"Alegreya Sans\",\"LXGW WenKai Screen\""
    description = "Accept who we really are"
    enableAutoAttribution = true
    enableTypographicalHyphenation = true
    privacyPolicyUrl = "/privacy/"
    jsdFontUrl= "https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@latest/style.min.css"
    GoogleFontUrl= "https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@800&family=Alegreya:ital,wght@0,400;0,700;1,400&family=IBM+Plex+Mono:ital@0;1&family=Noto+Serif+SC:wght@400;600&display=swap"
    localFontUrl = "/fonts/ZhuqueFangsong-Regular/results.css"
    [params.dropCap]
      enable = false

[related]
threshold = 80
includeNewer = true
toLower = true
  [[related.indices]]
  name = "tags"
  weight = 100

[outputs]
home = [ "HTML", "JSON", "RSS" ]
page = [ "HTML" ]

[markup.goldmark.extensions]
linkify = false

[sitemap]
changefreq = "weekly"
priority = 0.5