baseURL = "https://herbhuang.com/"
defaultContentLanguage = "en"
title = "🪴 Herb's Garden"
theme = "github.com/Masellum/hugo-theme-nostyleplease"
enableRobotsTXT = true
refLinksErrorLevel = "WARNING"
copyright = "This work is licensed under a Creative Commons BY-NC-SA 4.0 International License."
languageCode = "en-us"
googleAnalytics = ""



[language.zh]
weight = 2

[language.en]
weight = 1

[taxonomies]
tag = "tags"
category = "categories"

[minify]
disableXML = true

[minify.tdewolff.html]
keepQuotes = true

[outputs]
home = ["rss","atom","HTML" ]

[outputFormats.Atom]
name = "Atom"
mediaType = "text/xml"
baseName = "atom"
rel = "alternate"
isPlainText = false
isHTML = false
noUgly = true
permalinkable = false

[outputFormats.MANIFEST]
name = "Manifest"
mediaType = "application/manifest+json"
baseName = "manifest"
rel = "manifest"
isPlainText = true
isHTML = false
noUgly = false
notAlternative = true

[outputFormats.humanstxt]
mediaType = "text/plain"
baseName = "humans"
rel = "author"
isPlainText = true
isHTML = false
noUgly = true
permalinkable = false
notAlternative = true

[mediaTypes."text/xml"]
suffixes = [ "xml" ]

[mediaTypes."application/feed+json"]
suffixes = [ "json" ]

[mediaTypes."application/manifest+json"]
suffixes = [ "webmanifest" ]

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[author]
name = "Herb Huang"
email = "me@herbhuang.com"


[frontmatter]
lastmod = [ "lastmod", ":git", "date", "publishDate" ]

[module.hugoVersion]
extended = true
min = "0.95.0"

[[module.imports]]
path = "github.com/Masellum/hugo-theme-nostyleplease"

[params."params.theme_config"]
appearance = "auto"
back_home_text = ".."
date_format = "2006-01-02"
show_description = true

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
hl_inline = false
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = "onedark"
tabWidth = 4

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = false
